name: My Flow Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu
        steps:
            - name: Welcome Mssg
              run: echo "My first GithubAction Job"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md
